### ISSUE TITLE
Error message after first installation of knossos (no specifics)

### ISSUE THREAD

**Issue by shodanx2** [ngld/knossos#33]
Screenshot
https://i.imgur.com/NFhrwAQ.png

Unfortunately no error message
knossos v 0.14.3

**Comment by ngld** [comment]
Wrong repo. This repo contains the rewritten version of Knossos which hasn't been released, yet. The repo for old Knossos (0.14.3 and earlier) is here: https://github.com/ngld/old-knossos

However, this bug is unlikely to be fixed in the old version since I'm currently finished on the rewrite (which will fix the issue anyway).
