### ISSUE TITLE
Stranded in browser without a back button

### ISSUE THREAD

**Issue by shodanx2** [ngld/knossos#34]
Following links can leave you stranded in the browser without a back button
Requires application restart to fix

Example

https://i.imgur.com/nKnz38n.png

For example following the video link which might fail to load, then right clicking on it 
https://i.imgur.com/zAaBaVz.png

Will leave you in the above state (since the video was the only link to outside documentation for this mod, I had no other method)

**Comment by shodanx2** [comment]
Solution could be to leave the Home/explore/develop visible at all times

**Comment by ngld** [comment]
This isn't relevant to NuKnossos (this repo) since the rewritten version uses a very different UI architecture and can't end up in this state.

Right-click > Back should take you back into the Knossos interface. This issue is an unfortunate side-effect caused by the way old Knossos implements its UI. A user should never get in this state to begin with since the source code view isn't particularly useful and replaces the normal UI area.
